[package]
name = "slices"
version = "0.1.0"
authors = ["Yao Le <le.yao@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
